  version: 2.1
  orbs:
    terraform: circleci/terraform@1.0.2
  workflows:
    deploy_infrastructure:
      
      jobs:
        
        
        - terraform/fmt:
            checkout: true
            context: ec2
        - terraform/validate:
            checkout: true
            context: terraform
            requires:
              - terraform/fmt
        - terraform/plan:
            checkout: true
            persist-workspace: true
            context: terraform
            requires:
              - terraform/validate
        - terraform/apply:
            attach-workspace: true
            context: terraform
            requires:
              - terraform/plan
            filters:
              branches:
                only: master
