name: Terraform Apply

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      

    - name: setting up environment variables for AWS Keys
      run: |
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - run: cd ec2  

    - name: Terraform Init
      run: |
        #cd ec2
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        #cd ec2
        terraform plan -out saved_plan
